# Generated by Django 5.2.5 on 2025-08-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_data_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('Unimed', 'Unimed'), ('Particular', 'Particular'), ('Pladisa', 'Pladisa')], default='Particular', max_length=20),
        ),
    ]
