# Generated by Django 5.2.5 on 2025-08-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_consulta_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('Plano de Saude', 'Plano de Saude'), ('Particular', 'Particular')], default='Particular', max_length=20),
        ),
    ]
